"""my database today

Revision ID: c9d7668fef15
Revises: 
Create Date: 2022-06-24 16:13:34.067988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d7668fef15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('roles', sa.Boolean(), nullable=True),
    sa.Column('image_file', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('about_me', sa.String(), nullable=True),
    sa.Column('fb_name', sa.String(), nullable=True),
    sa.Column('ig_name', sa.String(), nullable=True),
    sa.Column('twt', sa.String(), nullable=True),
    sa.Column('lnk', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
